serviceAccount:
  create: false

auth:
  enablePostgresUser: true
  postgresPassword: "Pichincha1"
  username: "pluaj"
  password: "Pichincha1"
  database: "dbUsuarios"

architecture: standalone
primary:
  persistence:
    enabled: true
    storageClass: ""
    size: 5Gi
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
metrics:
  enabled: false
