serviceAccount:
  create: false
  # Usará el ServiceAccount "default" del namespace

auth:
  enablePostgresUser: true
  postgresPassword: "Pichincha1"
  username: "pluaj"
  password: "Pichincha1"
  database: "dbUsuarios"

architecture: standalone

primary:
  persistence:
    enabled: true
    storageClass: ""
    size: 5Gi
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  containerSecurityContext:
    enabled: false
  
  podSecurityContext:
    enabled: false
  
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
  
  podAnnotations:
    openshift.io/scc: restricted-v2

volumePermissions:
  enabled: false

shmVolume:
  enabled: false

postgresql:
  maxConnections: "100"
  sharedBuffers: "128MB"

metrics:
  enabled: false

diagnosticMode:
  enabled: false