image:
  repository: postgres
  tag: "18.0.0"
  pullPolicy: IfNotPresent

postgresql:
  username: pluaj
  password: Pichincha1
  database: dbUsuario

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

securityContext:
  runAsUser: 999
  runAsGroup: 999
