name: CI-CD-OpenShift-DB

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install OC CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz          
          sudo mv oc /usr/local/bin/
          oc version
      - name: Validate Namespace Context
        run: |
          echo "Validando contexto en namespace pluaj-dev-dev"
          oc project pluaj-dev-dev
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Login in Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.rm3.7wse.p1.openshiftapps.com:6443
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      - name: Deploy Base PostgreSQL via Helm
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm upgrade --install postgresql bitnami/postgresql  --set image.tag=${{ env.POSTGRES_VERSION || '15.5.0' }} --values values.yaml
    